### ISSUE TITLE
Some icons missing in hourly forecast

### ISSUE THREAD

**Issue by hennk** [outon/HomeAssistant-AEMET#7]
First of all thanks for this great component.

Lately I've noticed that in the hourly forecast details window, for some types of weather conditions, there isn't any icon shown.

![Screenshot from 2019-12-05 10-36-23](https://user-images.githubusercontent.com/328259/70223014-280abd80-174b-11ea-820a-9864c24c6b1a.png)

I am using the latest version of Hass, and latest aemet component from master as of yesterday.

Any idea why?

**Comment by outon** [comment]
Problem becomes because not all AEMET weather conditions are mapped to HA conditions and HA havent' provided the posibility to display your own icons or conditions descriptions

AEMET haven't published a full list of weather conditions. Mostly all missing icons are for night weather conditions. 

All mapping are on file [const.py](aemet/const.py) at line 159, feel free to do a pull request with those conditions that you have found to be missing, its description in English and a comment in spanish.

### How to find the weather condition as an AEMET code:

Go to [Predicción por municipios](http://www.aemet.es/es/eltiempo/prediccion/municipios), find your nearest town/city and select **Predicción por horas**

![image](https://user-images.githubusercontent.com/6525261/70379803-ceb0b300-1931-11ea-97b7-ad3b4ebe36ad.png)

On new page you will find a link to **Descargar XML de la predicción por horas de ...** , in that file you will find the weather condition:

Example:
`<estado_cielo periodo="14" descripcion="Muy nuboso">15</estado_cielo>`

> Meaning
> ```
> periodo = 14 (hour)
> Code: 15 
> Description: Muy nuboso
> ```

![image](https://user-images.githubusercontent.com/6525261/70379821-4ed71880-1932-11ea-8c4f-5e882863fb35.png)
